/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.GeneralController;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.Inventory;

/**
 *
 * @author cdvv
 */
public class InformationPanel extends javax.swing.JPanel {

   
    private final GeneralController generalController;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form InformationPanel
     */
    public InformationPanel() {
        generalController  = GeneralController.getGeneralController();
        initComponents();
        tableModel = (DefaultTableModel)tbInventoryData.getModel();
        poblateTable();
    }
    
    private void poblateTable() {
        int j = tableModel.getRowCount();
        for (int i = 0; i < j; i++) {
          tableModel.removeRow(0);  
        }
        Inventory userInventory = generalController.getUserInventory();
        tableModel.addRow(new Object[] {"Demanda esperada", userInventory.getExpectedDemand()});
        tableModel.addRow(new Object[] {"Precio de la unidad", userInventory.getUnitaryPrice()});
        tableModel.addRow(new Object[] {"Costo de orden", userInventory.getOrderingUnitaryCost()});
        tableModel.addRow(new Object[] {"Costo unitario al almacenar", userInventory.getStoringUnitaryCost()});
        tableModel.addRow(new Object[] {"Cantidad de unidades óptima", userInventory.getUnitsToStore()});
        tableModel.addRow(new Object[] {"Costo total por órdenes", userInventory.getTotalOrderingCost()});
        tableModel.addRow(new Object[] {"Costo total por almacenaje", userInventory.getTotalStoringCost()});
        tableModel.addRow(new Object[] {"Costo total de las unidades", userInventory.getTotalUnitsCost()});
        tableModel.addRow(new Object[] {"Costo total general", userInventory.getTotalCost()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spInformationTable = new javax.swing.JScrollPane();
        tbInventoryData = new javax.swing.JTable();

        tbInventoryData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Demanda esperada", null},
                {"Precio de la unidad", null},
                {"Costo de ordenar", null},
                {"Costo de inventariado por unidad", null},
                {"Cantidad de unidades óptima", null},
                {"Costo total para ordenar", null},
                {"Costo total de inventariado", null},
                {"Costo total general", null}
            },
            new String [] {
                "Valores", "Caso 1"
            }
        ));
        tbInventoryData.setEnabled(false);
        tbInventoryData.setMaximumSize(new java.awt.Dimension(250, 100));
        tbInventoryData.setMinimumSize(new java.awt.Dimension(30, 100));
        tbInventoryData.setPreferredSize(new java.awt.Dimension(900, 160));
        spInformationTable.setViewportView(tbInventoryData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spInformationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spInformationTable, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spInformationTable;
    private javax.swing.JTable tbInventoryData;
    // End of variables declaration//GEN-END:variables
}
