/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.GeneralController;
import controllers.UIController;
import java.util.HashSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author cdvv
 */
public class MainWindow extends javax.swing.JFrame {

    private final GeneralController generalController;
    private final UIController uIController;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.generalController = GeneralController.getGeneralController();
        this.uIController = UIController.getUIController();
        initComponents();
        ResultsLabel.setVisible(false);
        JScrollPane scroll = new JScrollPane();
        this.getContentPane().add(scroll);
        this.setSize(969,900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        SunbrightLabel = new javax.swing.JLabel();
        eoqLabel = new javax.swing.JLabel();
        DemandaEsperadaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PrecioTextField = new javax.swing.JTextField();
        CostoAlmaceTextField = new javax.swing.JTextField();
        CostoTextField = new javax.swing.JTextField();
        CalculateBtn = new javax.swing.JButton();
        SeparatorPanel = new javax.swing.JPanel();
        resultsPanel = new javax.swing.JPanel();
        ResultsLabel = new javax.swing.JLabel();
        resultsPanel1 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setSize(new java.awt.Dimension(1000, 900));

        LeftPanel.setBackground(new java.awt.Color(227, 243, 243));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/f0ee5783540344eea0050f65ff12f81b (1).png"))); // NOI18N

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RightPanel.setBackground(new java.awt.Color(128, 210, 200));

        SunbrightLabel.setText("Sunbright Citrus Products ®");

        eoqLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        eoqLabel.setForeground(new java.awt.Color(227, 243, 243));
        eoqLabel.setText("Control de inventarios (EOQ)");

        DemandaEsperadaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemandaEsperadaTextFieldActionPerformed(evt);
            }
        });
        DemandaEsperadaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DemandaEsperadaTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setText("Demanda esperada:");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setText("Precio de la unidad:");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel5.setText("Costo por ordenar:");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel6.setText("Costo de almacenaje unitario:");

        PrecioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTextFieldActionPerformed(evt);
            }
        });
        PrecioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioTextFieldKeyTyped(evt);
            }
        });

        CostoAlmaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoAlmaceTextFieldActionPerformed(evt);
            }
        });
        CostoAlmaceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoAlmaceTextFieldKeyTyped(evt);
            }
        });

        CostoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoTextFieldActionPerformed(evt);
            }
        });
        CostoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoTextFieldKeyTyped(evt);
            }
        });

        CalculateBtn.setBackground(new java.awt.Color(227, 243, 243));
        CalculateBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CalculateBtn.setText("Ver resultados");
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SunbrightLabel))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(RightPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CostoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(67, 67, 67)
                                    .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RightPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DemandaEsperadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(RightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CalculateBtn)
                                    .addComponent(CostoAlmaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(eoqLabel)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(eoqLabel)
                .addGap(108, 108, 108)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DemandaEsperadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CostoAlmaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(CalculateBtn)
                .addGap(12, 12, 12)
                .addComponent(SunbrightLabel)
                .addContainerGap())
        );

        SeparatorPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout SeparatorPanelLayout = new javax.swing.GroupLayout(SeparatorPanel);
        SeparatorPanel.setLayout(SeparatorPanelLayout);
        SeparatorPanelLayout.setHorizontalGroup(
            SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SeparatorPanelLayout.setVerticalGroup(
            SeparatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        resultsPanel.setBackground(new java.awt.Color(128, 210, 200));
        resultsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        ResultsLabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        ResultsLabel.setText("RESULTADOS");

        resultsPanel1.setBackground(new java.awt.Color(128, 210, 200));
        resultsPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout resultsPanel1Layout = new javax.swing.GroupLayout(resultsPanel1);
        resultsPanel1.setLayout(resultsPanel1Layout);
        resultsPanel1Layout.setHorizontalGroup(
            resultsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        resultsPanel1Layout.setVerticalGroup(
            resultsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(ResultsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addComponent(SeparatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeparatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RightPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(ResultsLabel)
                .addGap(18, 18, 18)
                .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemandaEsperadaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemandaEsperadaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemandaEsperadaTextFieldActionPerformed

    private void PrecioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTextFieldActionPerformed

    private void CostoAlmaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoAlmaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoAlmaceTextFieldActionPerformed

    private void CostoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoTextFieldActionPerformed

    private void DemandaEsperadaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DemandaEsperadaTextFieldKeyTyped
        if (DemandaEsperadaTextField.getText().length() >= 10) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (DemandaEsperadaTextField.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_DemandaEsperadaTextFieldKeyTyped

    private void PrecioTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioTextFieldKeyTyped
         if (PrecioTextField.getText().length() >= 10) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (PrecioTextField.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_PrecioTextFieldKeyTyped

    private void CostoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoTextFieldKeyTyped
        if (CostoTextField.getText().length() >= 10) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (CostoTextField.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_CostoTextFieldKeyTyped

    private void CostoAlmaceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoAlmaceTextFieldKeyTyped
        if (CostoAlmaceTextField.getText().length() >= 10) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (CostoAlmaceTextField.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_CostoAlmaceTextFieldKeyTyped

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
        int expectedDemand = Integer.parseInt(DemandaEsperadaTextField.getText());
        double unitaryPrice = Double.parseDouble(PrecioTextField.getText());
        double orderingCost = Double.parseDouble(CostoTextField.getText());
        double storingCost = Double.parseDouble(CostoAlmaceTextField.getText());
        generalController.createUserInventory(expectedDemand, unitaryPrice, orderingCost, storingCost);
        uIController.popUpMessage("Se han ingresado correctamente los datos", "Datos guardados", this.getParent());
       
        if(generalController.getUserInventory() == null) {
            uIController.popUpErrorMessage("No se han guardado los datos para poder realizar los cálculos", "Error", rootPane);
        } else {
            uIController.popUpMessage("Los datos se calcularon satisfactoriamente", "Datos calculados", rootPane);
        }
       
        resultsPanel.removeAll();
        InformationPanel pnInfo = new InformationPanel();
        pnInfo.setSize(resultsPanel.getWidth(), resultsPanel.getHeight());
        pnInfo.setAlignmentX(resultsPanel.getAlignmentX());
        pnInfo.setAlignmentY(resultsPanel.getAlignmentY());
        pnInfo.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        resultsPanel.add(pnInfo);
        pnInfo.revalidate();
        pnInfo.repaint();
        resultsPanel.revalidate();
        resultsPanel.repaint();
        
        resultsPanel1.removeAll();
        ComparationPanel pnComp = new ComparationPanel();
        pnComp.setSize(resultsPanel1.getWidth(), resultsPanel1.getHeight());
        pnComp.setAlignmentX(resultsPanel1.getAlignmentX());
        pnComp.setAlignmentY(resultsPanel1.getAlignmentY());
        pnComp.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        resultsPanel1.add(pnComp);
        pnComp.revalidate();
        pnComp.repaint();
        resultsPanel1.revalidate();
        resultsPanel1.repaint();
        
        ResultsLabel.setVisible(true);





    }//GEN-LAST:event_CalculateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainWindow mainWindow = new MainWindow();
            mainWindow.setVisible(true);
            mainWindow.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JTextField CostoAlmaceTextField;
    private javax.swing.JTextField CostoTextField;
    private javax.swing.JTextField DemandaEsperadaTextField;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JTextField PrecioTextField;
    private javax.swing.JLabel ResultsLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel SeparatorPanel;
    private javax.swing.JLabel SunbrightLabel;
    private javax.swing.JLabel eoqLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JPanel resultsPanel1;
    // End of variables declaration//GEN-END:variables
}
